name: autorun-black

on:
  pull_request

jobs:
  autorun-black:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install black
      run: pip install black

    - name: Run black
      run: git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF | grep "*.py" | xargs black

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Format code with black